apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hermes-app
  namespace: argocd
spec:
  project: default
  source:
    # URL do seu repositório criado no GitHub (Substitua pelos seus dados!)
    repoURL: 'https://github.com/Dolfino/Agent_Hermes.git'
    targetRevision: HEAD
    path: k8s
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: hermes
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
