apiVersion: v1
kind: Service
metadata:
  name: hermes-app
  namespace: hermes
  labels:
    app.kubernetes.io/name: hermes-app
    app.kubernetes.io/part-of: hermes
spec:
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: hermes-app
